# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: updateReadmeMetrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
#   push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    env:
        SCRIPT_MANAGER_API_CLIENT_ID: ${{ secrets.SCRIPT_MANAGER_API_CLIENT_ID }}
        SCRIPT_MANAGER_API_CLIENT_SECRET: ${{ secrets.SCRIPT_MANAGER_API_CLIENT_SECRET }}
        SCRIPT_MANAGER_API_ENDPOINT: ${{ secrets.SCRIPT_MANAGER_API_ENDPOINT }}
        MY_SCRIPT_NAME: 'landmaster135'
        THIS_FUNCTION_NAME: 'updateReadmeMetrics'
    steps:
      - name: Github_Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token here: https://github.com/settings/tokens
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: landmaster135
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
#           plugin_skyline: yes
#           plugin_skyline_frames: 60
#           plugin_skyline_quality: 0.5
#           plugin_skyline_year: current-year

      - name: Github_Metrics_Anilist
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: github-metrics-anilist.svg
          token: NOT_NEEDED
#           use_prebuilt_image: yes
#           delay: 60
          user: landmaster135
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: anime, characters
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 3
          plugin_anilist_user: kinkinbeer135ml
#           plugin_anilist_shuffle: yes
          plugin_anilist_limit_characters: 10
#           plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}

      - name: Record log
        run: |
          curl '${{ env.SCRIPT_MANAGER_API_ENDPOINT }}?scriptname=${{ env.MY_SCRIPT_NAME }}&function-name=${{ env.THIS_FUNCTION_NAME }}' \
          -L \
          -H "Content-Type: application/json" \
          -d '{"path": "/log", "method": "POST", "client_info": {"id": "${{ env.SCRIPT_MANAGER_API_CLIENT_ID }}", "secret": "${{ env.SCRIPT_MANAGER_API_CLIENT_SECRET }}"}}'
